# Generated by Django 5.2.8 on 2025-11-30 01:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_standardpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('embed', 1), ('gallery', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page whose children should be displayed in this gallery'}), 3: ('wagtail.blocks.StructBlock', [[('page', 2)]], {})}, null=True),
        ),
    ]
