# Generated by Django 5.2.8 on 2025-11-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPage',
        ),
    ]
