# Generated by Django 5.2.8 on 2025-11-29 04:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_delete_gallerypage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
        migrations.AddField(
            model_name='artpage',
            name='dimensions',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='artpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='artpage',
            name='medium',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='artpage',
            name='print_prices',
            field=wagtail.fields.StreamField([('price_tier', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.FloatBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('dimensions', 0), ('prices', 1)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='artpage',
            name='prints_available',
            field=models.BooleanField(default=False),
        ),
    ]
