# Generated by Django 5.2.8 on 2025-11-29 04:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artpage_body_artpage_dimensions_artpage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='print_prices',
            field=wagtail.fields.StreamField([('price_tier', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.FloatBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('dimensions', 0), ('prices', 1)]], {})}, null=True),
        ),
    ]
