# Generated by Django 5.2.8 on 2025-11-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_artpage_print_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artpage',
            old_name='body',
            new_name='description',
        ),
    ]
