# Generated by Django 5.2.8 on 2025-11-29 18:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_body_artpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='print_prices',
            field=wagtail.fields.StreamField([('price_tier', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.FloatBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('dimensions', 0), ('price', 1)]], {})}, null=True),
        ),
    ]
