# Generated by Django 5.2.8 on 2025-11-28 06:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sidebar',
            field=wagtail.fields.StreamField([('sidebar_content', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StreamBlock', [[('rich_text', 1)]], {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 2)]], {})}, null=True),
        ),
    ]
