# Generated by Django 5.2.8 on 2025-12-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='watermark_text',
            field=models.CharField(blank=True, help_text='Printed onto images when a watermark is necessary.', max_length=255, null=True),
        ),
    ]
