# Generated by Django 5.2.8 on 2025-12-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_watermark_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='watermark_text',
            field=models.TextField(blank=True, help_text='Printed onto images when a watermark is necessary.', null=True),
        ),
    ]
